version: "3.8"

services:
  web:
    image: ${DOCKER_IMAGE:-ghcr.io/aaacoder-ds/file-privacy-inspector:latest}
    restart: unless-stopped
    ports:
      - "3086:80" # Optional for local testing; reverse proxy will handle the domain in Dokploy
    environment:
      - NODE_ENV=production
